Dimemas3_SOURCES += \
  model/communic.c \
  model/communic.h \
  model/cpu.c \
  model/cpu.h \
  model/fs.c \
  model/fs.h \
  model/links.c \
  model/links.h \
  model/memory.c \
  model/memory.h \
  model/ports.c \
  model/ports.h \
  model/semaphore.c \
  model/semaphore.h \
  model/task.c \
  model/task.h \
  model/thread_states.c \
  model/thread_states.h
  
Dimemas3_CFLAGS += -Imodel
Dimemas3_CXXFLAGS += -Imodel
  
# noinst_HEADERS +=  
# model_INCLUDES = 

