venusclient_CPPSRCS = \
  $(top_srcdir)/src/venusclient/ClientSocket.cc \
  $(top_srcdir)/src/venusclient/Socket.cc \
  $(top_srcdir)/src/venusclient/venusclient.cc

venusclient_SRCS = 

venusclient_OBJS = $(venusclient_CPPSRCS:.cc=.o) $(venusclient_SRCS:.c=.o)

venusclient_INCLUDES = -I$(top_srcdir)/src/venusclient

