defaultsdir=$(datadir)/dimemas_defaults

defaults_FILES= \
  defaults/Dimemas \
  defaults/Gui \
  defaults/header.txt \
  defaults/icon.jpg \
  defaults/machines.db \
  defaults/Makefile.sources \
  defaults/networks.db

EXTRA_DIST = $(defaults_FILES)

install-exec-hook:
	$(mkdir_p) $(defaultsdir)
	cp $(defaults_FILES) $(defaultsdir)

