Dimemas3_SOURCES += \
  prv_utils/MPI_EventEncoding.h \
  prv_utils/paraver.c \
  prv_utils/paraver.h \
  prv_utils/paraver_pcf.c \
  prv_utils/paraver_pcf.h

Dimemas3_CFLAGS += -Iprv_utils
Dimemas3_CXXFLAGS += -Iprv_utils

# noinst_HEADERS += 

# prv_utils_OBJS = $(prv_utils_SRCS:.c=.o)

# prv_utils_INCLUDES = 
