Dimemas3_SOURCES += \
  utils/aleatorias.c \
  utils/aleatorias.h \
  utils/cp.c \
  utils/cp.h \
  utils/list.c \
  utils/list.h \
  utils/mallocame.c \
  utils/mallocame.h \
  utils/random.c \
  utils/random.h \
  utils/subr.c \
  utils/subr.h

Dimemas3_CFLAGS += -Iutils
Dimemas3_CXXFLAGS += -Iutils

# noinst_HEADERS += \
# utils_OBJS = $(utils_SRCS:.c=.o)

#utils_INCLUDES = -I utils

