/**
 * -- DO NOT EDIT THIS FILE --
 * This file is generated automatically during the build process
 * (./configure && make) based on the standard GNU Auto-tools.
 */
package data;

public interface Version {

    public String versionString = "Dimemas Graphical User Interface 5.4.2";

}
